language: node_js
node_js:
  - 8
cache:
  directories:
  - web/node_modules
before_install:
  - cd web
notifications:
  email: false
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: web/build
  on:
    branch: master
